### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by Dylantje** [damalis/full-stack-apache2-wordpress-for-everyone-with-docker-compose#2]
Hi,

Try your expert script...
Looking great, only:
![image](https://github.com/damalis/full-stack-apache2-wordpress-for-everyone-with-docker-compose/assets/5214969/2b5ec805-4749-41bb-a4c2-4c798a728fa6)
Cannot go on..
Whats the format i need to type??
Can i set perhaps the script that is not install docker?
I run some docker images, using docker compose.
Now uninstall and install the script some...
Can i change the docker compose and run then the yml file?
Perhaps you have a example?

Thanks!!!

**Comment by damalis** [comment]
I tried and did'nt get any error 

OS: `Ubuntu 1 GB RAM, 2 vCPUs, 40 GB SSD` at aws lightsail
